mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from recipes.views import recipe_list, recipe_detail, index, storage_index
from accounts.views import login, register, logout

app_name = "MANAGER"
urlpatterns = [
    path('', index, name="index"), ## include('recipes.urls')
    path('recipes', include('recipes.urls')),
    path('admin/', admin.site.urls),
    path('login', login, name="login"),
    path('register', register, name="register"),
    path('logout', logout, name="logout"),
    path("meal-tracker", include('tracker.urls')),
    path("storage", storage_index, name="storage-index")
]

mysite/recipes/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = "recipes"
urlpatterns = [
    path('', views.recipe_list, name="recipe_list"),
    path("details/<int:recipe_id>/", views.recipe_detail, name="recipe_detail"),
]

mysite/tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import tracker_index


app_name = "tracker"

urlpatterns = [path('', tracker_index, name="tracker_index")]

mysite/recipes/models.py
from django.db import models
from django.contrib import auth
from datetime import timedelta
from django.utils import timezone

def in_three_days():
    return timezone.now() + timedelta(days=3)

class Ingredient(models.Model):
    name = models.CharField(max_length=30)
    packetQuantityGrams = models.PositiveIntegerField(default=0)
    price = models.DecimalField(max_digits=5, decimal_places=2, default=0)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Recipe(models.Model):
    name = models.CharField(max_length=100)
    ingredients = models.ManyToManyField(Ingredient, through='RecipeIngredient')
    instructions = models.CharField(max_length=5000, default="No detailed Instructions")

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

class RecipeIngredient(models.Model):
    rname = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    iname = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    recipeQuantityGrams = models.DecimalField(max_digits=8, decimal_places=4, default=0)

class StorageUnit(models.Model):
    ### Stores cupboard and fridge items
    owner = models.ForeignKey(auth.models.User, on_delete=models.CASCADE)
    ingredients = models.ManyToManyField(Ingredient, through='StorageIngredient')

    def __str__(self):
        return f"{self.owner.__str__()}'s Unit"
class StorageIngredient(models.Model):
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    storage_unit = models.ForeignKey(StorageUnit, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    isFridge = models.BooleanField(default=False)
    stored_at = models.DateTimeField(auto_now_add=True)
    expires_at = models.DateTimeField(default=in_three_days)
    
    def __str__(self):
        return f"{self.ingredient.__str__()} is stored in {self.storage_unit.__str__()}"

mysite/tracker/models.py
from django.db import models

# Create your models here.

mysite/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login as auth_login, authenticate, logout as auth_logout
from django.contrib import messages
# Create your views here.


def login(request):
    if request.method == "POST":

        user = authenticate(request, username=request.POST["username"], password=request.POST["password"])
        auth_login(request, user)
        if user is None:
            context = {"error":"Invalid username or password"}
            return render(request, "accounts/login.html", context)
        
        return redirect("index")
    return render(request, "accounts/login.html")
def register(request):
    #print(request, "HERE", request.POST)
    if request.user.is_authenticated:
        return redirect("index")
    
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            
            return redirect("index")
        ### Failed to register user
        print(form.errors.as_text)
        context = {"errors": form.errors.as_text}
        return render(request, "accounts/register.html", context)
    return render(request, "accounts/register.html")

def logout(request):
    auth_logout(request)

    return redirect("index")

mysite/recipes/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.

from .models import Recipe, RecipeIngredient, StorageUnit


def recipe_list(request):

    recipes = Recipe.objects.all()
    rdetails = {}
    for recipe in recipes:
        #print(recipe.name, "HERE WITH ID", recipe.id)
        res = RecipeIngredient.objects.filter(rname=recipe.id)
        # for i in res:
        #     print("FOUND Ingredient", i.rname, i.iname, i.recipeQuantityGrams)
        rdetails[recipe] = res
        #print(res, recipe.name)
        
    context = {"recipes":recipes, "rdetails":rdetails}

    return render(request, "recipes/all_recipes.html", context)

def recipe_detail(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    return render(request, "recipes/recipe_detail.html", {"recipe":recipe})

def index(request):

    context = {}
    return render(request, "recipes/index.html", context)

def meal_planner(request):
    return render(request, "BLAH")

def storage_index(request):
    store_units = StorageUnit.objects.filter(owner=request.user)
    assert len(store_units) == 1
    store_unit = store_units[0]
    fridge_ings = store_unit.ingredients.filter(storageingredient__isFridge=True)
    print(fridge_ings)
    print(store_unit)
    context = {"fridge_ings":fridge_ings}




    return render(request, "storage/index.html", context)

mysite/tracker/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
# Create your views here.


@login_required
def tracker_index(request):
    return render(request, "tracker/index.html")

mysite/recipes/templates/recipes/all_recipes.html
{% extends "recipes/base.html" %}
{% block content %}
{%load static%}
<div class="text-center bg-secondary-subtle">
    <div class="h1"> Recipes </div>
</div>
<div class="container-lg my5">
    {% comment %} <img src="{% static 'recipes/fuji-bg.jpg' %}" alt="My image" class="bg-image bg-cover"> {% endcomment %}
    
    
    {% if recipes %}
        <div class="row mb-3 bg-light text-light">
            {% for recipe, vals in rdetails.items %}


                <div class="col justify-content-center d-flex">
                    {% comment %} <div class="p-5 bg-secondary text-light rounded">
                            <div class="h3 text-light text-center"> {{recipe.name}} </div>
                            <ul class="list-group">
                                {% for ing in recipe.ingredients.all %}
                                    <div class="list-group-item">
                                        <div class="text-left">{{ing}} </div>
                                    </div>
                                {% endfor %}
                            </ul>
                    </div> {% endcomment %}
                    <div class="card bg-secondary text-light" style="width: 24rem;">
                        <img src="{% static 'recipes/beef-stir-fry.jpg' %}" class="card-img-top" alt="...">
                        <div class="card-body">
                          <h5 class="card-title">{{recipe.name}}</h5>
                          <ul class="list-group">
                            {% for ing in vals %}
                                <div class="list-group-item">
                                    <div class="text-left">{{ing.iname}} ({{ing.recipeQuantityGrams|floatformat}}g)  </div>
                                </div>
                            {% endfor %}
                        </ul>
                          <a href="{% url 'recipes:recipe_detail' recipe.id %}" class="btn btn-light mt-3">Recipe details</a>
                        </div>
                      </div>
                    
                </div>

            {% endfor %}
        </div>

    {% else %}
    <h3> No recipes to display </h3>

    {% endif %}
</div>
{%endblock content %}

mysite/recipes/templates/recipes/base.html
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <title>Recipe site!</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link href= "{% static 'recipes/style.css' %}" rel="stylesheet">
    {% load django_bootstrap5 %}

    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>
  <body>

    

    <nav class="navbar navbar-expand bg-dark navbar-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'recipes:home' %}">Home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Meal Tracker</a>
              </li>
            
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'recipes:recipe_list' %}">Recipes</a>
              </li>

              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Pantry/Fridge</a>
              </li>

              {% comment %} <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li> {% endcomment %}
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>


      
    
    
    {% block content%}
    {%endblock content%}



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
    

</body>

</html>

mysite/recipes/templates/recipes/index.html
{% extends "recipes/base.html" %}

{% block content%}
{% load static %}
<div class="d-flex vh-60 text-center text-bg-secondary py-5 justify-content-center">

  <main class="px-3">
    <div class="h1 my=3">Meal Tracker. Recipes. One place. </div>
    <p class="lead">Track your meals with our calendar and use AI to generate new exciting recipes.</p>
    <p class="lead"> Keep track of what's in your fridge and cupboards and get recipes for what you have on hand! </p>
    <p class="lead">
      <a href="#" class="btn btn-lg btn-light fw-bold border-white bg-white">Learn more</a>
    </p>
  </main>
</div>

<div class="container-fluid pt-3">

    <div class="row px-5">
        <div class="col-sm d-flex justify-content-center">
            <div class="card bg-secondary text-light" style="width: 18rem;">
                <img src="{% static 'recipes/chef-chopping.jpg' %}" class="card-img-top" alt="Chef chopping">
                <div class="card-body">
                  <h5 class="card-title">Custom recipes</h5>
                  <p class="card-text">
                    The site uses the latest AI to generate custom receipes for you. 
                  </p>
                  <a href="{% url 'recipes:recipe_list' %}" class="btn btn-primary">Start now</a>
                  
                </div>
              </div>
              
        </div>
        <div class="col-sm d-flex justify-content-center">
            <div class="card bg-secondary text-light" style="width: 18rem;">
                <img src="{% static 'recipes/fuji-bg.jpg' %}" class="card-img-top" alt="Chef chopping">
                <div class="card-body">
                  <h5 class="card-title">Peace of mind</h5>
                  <p class="card-text">
                    Don't like a recipe? <br> Get a new one at click of a button.
                  </p>
                  <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
              </div>
        </div>
        <div class="col-sm d-flex justify-content-center">
            <div class="card bg-secondary text-light" style="width: 18rem;">
                <img src="{% static 'recipes/food-variety.jpg' %}" class="card-img-top" alt="Chef chopping">
                <div class="card-body">
                  <h5 class="card-title">Tailored to your diet</h5>
                  <p class="card-text">
                    The AI adapts the meals to your meal history, ensuring you have the required nutrients for the week.
                  </p>
                  <a href="{% url 'recipes:meal_planner_home' %}" class="btn btn-primary">Start yours now.</a>
                </div>
              </div>
        </div>
        
    </div>
</div>

{% endblock content %}

mysite/recipes/templates/recipes/recipe_detail.html
{% extends "recipes/base.html" %}

{%block content%}
<h1> Recipe name: {{recipe.name}} </h1>
{%endblock content%}

mysite/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}

<div class = "container d-flex w-100 justify-content-center m-auto pt-5">
    <div class="h3 text-light">Please sign in</div>
</div>

<div class = "container d-flex align-items-center bg-body-tertiary text-light justify-content-center pt-5 mt-5 rounded-5">
    
    <form method="POST" action="">
        {% csrf_token %}
        <div class="mb-3">
            <label for="user_form" class="form-label"> Username </label>
            <input type="username" class="form-control" id="user_form" name="username">
        </div>

        <div class="mb-3">
            <label for="password" class="form-label"> Password </label>
            <input type="password" class="form-control" id="password" name="password">
        </div>

        {% if error %}
            <div class="mb-3">
                <p> {{ error }} </p>
            </div>

        {% endif %}

        <button class="btn btn-light w-100 py-2 my-3" type="submit"> Sign in </button>
    </form>

</div>

{% endblock %}

mysite/templates/accounts/register.html
{% extends "base.html" %}

{% block content %}

<div class = "container d-flex w-100 justify-content-center m-auto pt-5">
    <div class="h3 text-light">Please register</div>
</div>

<div class = "container d-flex align-items-center bg-body-tertiary text-light justify-content-center pt-5 mt-5 rounded-5">
    
    <form method="POST" action="">
        {% csrf_token %}
        <div class="mb-3">
            <label for="user_form" class="form-label"> Username </label>
            <input type="username" class="form-control" id="user_form" name="username">
        </div>

        <div class="mb-3">
            <label for="password1" class="form-label"> Password </label>
            <input type="password" class="form-control" id="password1" name="password1">
        </div>

        <div class="mb-3">
            <label for="password2" class="form-label"> Confirm password </label>
            <input type="password" class="form-control" id="password2" name="password2">
        </div>

        {% if errors %}
            <div class="mb-3">
                <p> {{ errors }} </p>
            </div>
        {% endif %}

        <button class="btn btn-light w-100 py-2 my-3" type="submit"> Register </button>
    </form>

</div>

{% endblock %}

mysite/templates/base.html
<!DOCTYPE html>

<html lang="en" data-bs-theme="dark">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <title>Recipe site!</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link href= "{% static 'recipes/style.css' %}" rel="stylesheet">
    {% load django_bootstrap5 %}

    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>
  <body class="bg-dark">

    

    <nav class="navbar navbar-expand navbar-dark border-bottom border-top border-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'index' %}">Home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                {% if user.is_authenticated %}
                  <a class="nav-link active" aria-current="page" href="{% url 'tracker:tracker_index' %}">Meal Tracker</a>
                {% else %}
                  <a class="nav-link disabled" aria-current="page" href="#" aria-disabled="true">Meal Tracker</a>
                {% endif %}
              </li>
              
              {%if not user.is_authenticated%}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'recipes:recipe_list' %}">Recipes</a>
              </li>
              {% else %}
              <li class="nav-item dropdown ">
                <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Recipe Options
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'recipes:recipe_list' %}">All recipes</a></li>
                  <li><a class="dropdown-item" href="#">My recipes</a></li>
                  {% comment %} <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li> {% endcomment %}
                </ul>
              </li>
              {% endif %}

              <li class="nav-item">
                {% if  user.is_authenticated%}
                <a class="nav-link active" aria-current="page" href="{% url 'storage-index' %}">Pantry/Fridge</a>
                {% else %}
                <a class="nav-link disabled" aria-current="page" href="{% url 'storage-index' %}" aria-disabled="true">Pantry/Fridge</a>
                {% endif %}
              </li>

              {% comment %} <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li> {% endcomment %}
              {% comment %} <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li>
            </ul> {% endcomment %}
            {% comment %} <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form> {% endcomment %}


          </div>

          <ul class="nav justify-content-end text-light">

            {% if not user.is_authenticated%}
            <li class="nav-item">
              <a class="nav-link active text-light" aria-current="page" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item mx-3">
              <a class="nav-link active text-light" aria-current="page" href="{% url 'register' %}">Register</a>
            </li>
            {% else %}
            <li class="nav-item mx-3">
              <a class="nav-link active text-light" aria-current="page" href="{% url 'logout' %}">Logout</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>

 
      
    
    
    {% block content%}
    {%endblock content%}



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
    

</body>

</html>

mysite/templates/recipes/all_recipes.html
{% extends "base.html" %}
{% block content %}
{%load static%}
<div class="text-center">
    <div class="h1 bg-secondary pb-3 pt-1 text-light"> Recipes </div>
</div>
<div class="container-lg my5">
    {% comment %} <img src="{% static 'recipes/fuji-bg.jpg' %}" alt="My image" class="bg-image bg-cover"> {% endcomment %}
    
    
    {% if recipes %}
        <div class="row mb-3 pt-5">
            {% for recipe, vals in rdetails.items %}


                <div class="col justify-content-center d-flex">
                    {% comment %} <div class="p-5 bg-secondary text-light rounded">
                            <div class="h3 text-light text-center"> {{recipe.name}} </div>
                            <ul class="list-group">
                                {% for ing in recipe.ingredients.all %}
                                    <div class="list-group-item">
                                        <div class="text-left">{{ing}} </div>
                                    </div>
                                {% endfor %}
                            </ul>
                    </div> {% endcomment %}
                    <div class="card bg-secondary text-light" style="width: 24rem;">
                        <img src="{% static 'recipes/beef-stir-fry.jpg' %}" class="card-img-top" alt="...">
                        <div class="card-body">
                          <h5 class="card-title">{{recipe.name}}</h5>
                          <ul class="list-group">
                            {% for ing in vals %}
                                <div class="list-group-item">
                                    <div class="text-left">{{ing.iname}} ({{ing.recipeQuantityGrams|floatformat}}g)  </div>
                                </div>
                            {% endfor %}
                        </ul>
                          <a href="{% url 'recipes:recipe_detail' recipe.id %}" class="btn btn-light mt-3">Recipe details</a>
                          {% if user.is_authenticated %}
                            <a href="" class="btn btn-light mt-3">Save recipe</a>
                          {% endif %}
                        </div>
                      </div>
                    
                </div>

            {% endfor %}
        </div>

    {% else %}
    <h3> No recipes to display </h3>

    {% endif %}
</div>
{%endblock content %}

mysite/templates/recipes/index.html
{% extends "base.html" %}

{% block content%}
{% load static %}
<div class="d-flex vh-60 text-center text-bg-secondary py-5 justify-content-center border-bottom border-light">

  <div class="px-3 ">
    <div class="h1 my=3">Meal Tracker. Recipes. One place. </div>
    <p class="lead">Track your meals with our calendar and use AI to generate new exciting recipes.</p>
    <p class="lead"> Keep track of what's in your fridge and cupboards and get recipes for what you have on hand! </p>
    <p class="lead">
      <a href="#" class="btn btn-lg btn-light fw-bold border-white bg-white">Learn more</a>
    </p>
  </div>
</div>

<div class="container-fluid pt-3">

    <div class="row px-5">
        <div class="col-sm d-flex justify-content-center">
            <div class="card bg-secondary text-light" style="width: 18rem;">
                <img src="{% static 'recipes/chef-chopping.jpg' %}" class="card-img-top" alt="Chef chopping">
                <div class="card-body">
                  <h5 class="card-title">Custom recipes</h5>
                  <p class="card-text">
                    The site uses the latest AI to generate custom receipes for you. 
                  </p>
                  <a href="{% url 'recipes:recipe_list' %}" class="btn btn-light fw-bold">Start now</a>
                  
                </div>
              </div>
              
        </div>
        <div class="col-sm d-flex justify-content-center order-3">
            <div class="card bg-secondary text-light" style="width: 18rem;">
                <img src="{% static 'recipes/fuji-bg.jpg' %}" class="card-img-top" alt="Chef chopping">
                <div class="card-body">
                  <h5 class="card-title">Peace of mind</h5>
                  <p class="card-text">
                    Don't like a recipe? <br> Get a new one at click of a button.
                  </p>
                  {% comment %} <a href="#" class="btn btn-primary">Go somewhere</a> {% endcomment %}
                </div>
              </div>
        </div>
        <div class="col-sm d-flex justify-content-center order-2">
            <div class="card bg-secondary text-light" style="width: 18rem;">
                <img src="{% static 'recipes/food-variety.jpg' %}" class="card-img-top" alt="Chef chopping">
                <div class="card-body">
                  <h5 class="card-title">Tailored to your diet</h5>
                  <p class="card-text">
                    The AI adapts the meals to your meal history, ensuring you have the required nutrients for the week.
                  </p>
                  {% if not user.is_authenticated %}
                    <a href="{% url 'register' %}" class="btn btn-light fw-bold">Start yours now.</a>
                  {% else %}
                    <a href="{% url 'recipes:recipe_list' %}" class="btn btn-light fw-bold">See yours now</a>
                  {% endif %}
                </div>
              </div>
        </div>
        
    </div>
</div>

{% endblock content %}

mysite/templates/recipes/recipe_detail.html
{% extends "base.html" %}

{%block content%}
<div class="h1 text-light"> Recipe name: {{recipe.name}} </div>
{%endblock content%}

mysite/templates/tracker/index.html
{% extends "base.html" %}

{% block content %}

<div class="h1 text-light"> Tracking page </div>

{% endblock %}